version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: places-api
    ports:
      - "7001:7001"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
